### ISSUE TITLE
Remove ignore of magical numbers from setup.cfg

### ISSUE THREAD

**Issue by AABur** [hexlet-boilerplates/python-package#4]
https://github.com/hexlet-boilerplates/python-package/blob/d823cd16d4ff7832a523fa37f26d658b91251aa8/setup.cfg#L15

It is not a good idea to ignore the linting on magic numbers globally. It is better to turn it off locally, where magic numbers are really required.

**Comment by corsicanec82** [comment]
https://github.com/hexlet-boilerplates/python-package/pull/5
